### ISSUE TITLE
KODI IP address is hard-coded into the script

### ISSUE THREAD

**Issue by tiny-e** [bite-your-idols/script.hyperion.switch#1]
Thanks for making this!

--
So, the notification fails and causes the script to fail also.  I was able to use `KODIIP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')`

and then `curl -v -H "Accept: application/json" -H "Content-type: application/json" -d '{"id":1,"jsonrpc":"2.0","method":"GUI.ShowNotification","params":{"title":"Hyperion","message":"Disabled","image":"/storage/.kodi/addons/script.hyperion.switch/icon.png"}}' http://$KODIIP:8080/jsonrpc`

and

`curl -v -H "Accept: application/json" -H "Content-type: application/json" -d '{"id":1,"jsonrpc":"2.0","method":"GUI.ShowNotification","params":{"title":"Hyperion","message":"Enabled","image":"/storage/.kodi/addons/script.hyperion.switch/icon.png"}}' http://$KODIIP:8080/jsonrpc`

to get it working. 

My fix assumes port 8080, not sure how to auto-determine the port KODI's http server is running on.

**Comment by bite-your-idols** [comment]
thanks for the fix!
